[package]
name = "xmt"
version = "0.1.0"
edition = "2021"
authors = ["William Dussault <william@dussault.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
once_cell = "1.10.0"
